### ISSUE TITLE
Adopt open-source library instead of IPP

### ISSUE THREAD

**Issue by guilhermelawless** [guilhermelawless/pfuclt_omni_dataset#1]
Intel® Integrated Performance Primitives (IPP) currently provides some functions regarding random number generation for uniform distribution and standard deviation for particles. It is desirable to move to an open-source library.

While doing this enchancement, let's make sure different distributions can be used to initialize particles.

**Comment by guilhermelawless** [comment]
Investigating GNU Scientific Library (GSL), currently on version 2.2.1

See https://www.gnu.org/software/gsl/

**Comment by aamirahmad** [comment]
Great! Just wanted to point out one more thing. IPP might have been used to create image data types as well. In the past I used to do that. Just make sure that it is all switched to opencv data types.

**Comment by guilhermelawless** [comment]
The evaluate package is using OpenCV already :)

The read package is getting ball coordinates directly as numbers - which means these are already in the rosbag file. Do you recall if this is accomplished in run-time? I am confused here.

**Comment by guilhermelawless** [comment]
In 7dc490f342a876eb73d4a0fbc1dc85d2ef020aa1 there are no more dependencies on IPP. Most functionality has been replaced by Boost and STL (no C++11 or 0x as ROS doesn't recommend it).

Might be slower than using IPP though. Would be interesting to compare with the no-ROS implementation, especially if online use is wanted.

**Comment by aamirahmad** [comment]
Answering your Q about ball coordinates: It is possible to directly access this prre-processed measurement data. A 3-D detection algorithm was run on the images to generate those measurements. If someone wants, can run their own detection algorithm also on the images. That is possible as well. By default, the ball messages are the pre-processed ones. Also, in the beginning I would say use that. Later we can talk about improving this detection. certo?

**Comment by aamirahmad** [comment]
Great thing abt IPP... I know IPP is usually faster that's why we had it in the first place. Problem is that it is not very open. Anyway, speed is an issue we should discuss and compare runtimes experimentally because PFs are notorious regarding that.

**Comment by guilhermelawless** [comment]
Ok, pre-processing definetely makes sense. Yes, I believe we should improve only one part at a time as well, later improving the algorithm if necessary.

About IPP, yes I had that feeling. Would you suggest going back to it then, or staying with what I developed?

**Comment by aamirahmad** [comment]
For now lets not go back to IPP. Lets keep opencv and GLS functions as you have probably done and compare ros and no-ros versions. But again, thats after everything is working flawlessly in ros.

**Comment by guilhermelawless** [comment]
Ok, i'll branch out this version. It does not use GLS though, only the standard C++ library and Boost.
Should I still move to a newer IPP version though? (2017)

**Comment by aamirahmad** [comment]
Lets have IPP again after pfuclt and its evaluation are tested thoroughly within ros at least.
We can talk more tomorrow.

**Comment by guilhermelawless** [comment]
Sorry, I read your previous comment completely wrong. Ok, i'll try to continue on this. If you have more info regarding the algorithm (pictures, a flow chart,..) it would be greatly appreciated.

See you tomorrow!

**Comment by aamirahmad** [comment]
If you have the latest version of the paper, it should have more or less all that I can give for now.

**Comment by guilhermelawless** [comment]
Moved to STL + Boost for now
