### ISSUE TITLE
Tune alpha parameters (odometry sampling)

### ISSUE THREAD

**Issue by guilhermelawless** [guilhermelawless/pfuclt_omni_dataset#10]
1. Use GT data to fit a distribution model (Gaussian) to the odometry using the 4 alpha values.
@aamirahmad send some guidelines over e-mail or add here

2. Add some heuristics

For reference:
> Alphas:
>   0 is uncertainty in rotation applied in rotation
>   1 is uncertainty in translation applied in rotation
>   2 is uncertainty in rotation applied in translation
>   3 is uncertainty in translation applied in translation

**Comment by guilhermelawless** [comment]
Regarding the calculations in the algorithm, I think they are wrong. Next time I pick this up I'll fix it according to AMCL:
https://github.com/ros-planning/navigation/blob/groovy-devel/amcl/src/sensors/amcl_odom.cpp#L184

Basically, we should be adding the variances and not std_devs. A discussion of this is in: http://answers.ros.org/question/54467/is-amcls-implementation-of-the-odometry-model-correct/

**Comment by guilhermelawless** [comment]
@aamirahmad  do you think we should update to the adding variances? Odometry is currently working fine but it would be more formally correct to do that.

The downside is that we'd have to find out the alphas for the real dataset if we want to use it again.

**Comment by aamirahmad** [comment]
@guilhermelawless Yes, we could leave it out for the moment and raise a red flag to correct in post submission versions. Could you please do something like that (and then close this issue.)?
