### ISSUE TITLE
Improve ball velocity estimator

### ISSUE THREAD

**Issue by guilhermelawless** [guilhermelawless/pfuclt_omni_dataset#11]

**Comment by guilhermelawless** [comment]
Currently there's one big issue. After some time where there's no target observations, the resampling process stops and particles spread out. Since it takes some time for the target particles to converge to the observation locations once we start seeing it again (related: #13 ), one specific behavior occurs:

The velocity estimation starts and due to jumps in observations from the latest, the ball particles can even go out of the field and never converge again.

I think the problem has 1 root:

1. Not clearing (resetting) the velocity estimator after we stop seeing the target

**Comment by guilhermelawless** [comment]
3492ba0d35c028a9ffb8d3d633c264460fff1458 Attempts to fix this issue. The velocity estimator is no longer reset at any time.

In case the target isn't seen in some iteration, the last known position is re-inserted. If the target isn't seen for some amount of iterations (the stack size), the ball will eventually have zero velocity. If the target is seen again, the behaviour will be a bit more jumpy.

In case of zero weightsum, the filter is not reset, as the target observations may still be correct if there is at least one robot with good conf. that sees the target continously.

**Comment by aamirahmad** [comment]
I partially understand this issue. What i do not get is the jumpy behavior of the velocity you explain. Shouldn't that be same even in normal situations? Or what you mean is that a sudden new observation (after big hole in observation) causes the velocity regressor to calculate a 'one' sudden high velocity and then the particles simply overshoot? If so, why not always clear the stack when the ball goes out of view? and then when it comes in view, wait again for some (maybe 10) consecutive observations to restart velocity regressor. During those velocity-downtimes just use a zero-velocity but a slightly higher acceleration noise in the prediction model?

**Comment by aamirahmad** [comment]
Ok, now I read the latest issue thread and seems like your idea was almost on the same lines!... more about it on the latest thread

**Comment by guilhermelawless** [comment]
Now disabled by default

**Comment by guilhermelawless** [comment]
Decided not to use at all.
