### ISSUE TITLE
Converge faster to the target estimation

### ISSUE THREAD

**Issue by guilhermelawless** [guilhermelawless/pfuclt_omni_dataset#13]
After no robot sees the target for some time, the estimation is wrong and sometimes it stops resampling (weight sum = 0) once we have target observations again.

We should find a way to make it more "jumpy" once we see the target again, as currently it takes a long time and since there's no resampling, the particles go all over the place.

**Comment by guilhermelawless** [comment]
@aamirahmad 
Improvements are seen in 6e4e14216cde85d4cec7733914609b2194f257e6 but these should be formalized going forward. The behaviour right now is as follows:

1. Having a higher expArg in the probability calculation in fuseRobots() and fuseTarget() causes the filter to have lower convergence time, as well as higher performance target tracking.

2. When target is lost (aka the robots don't see it, not just tracking by the filter is lost), the particles will spread a bit according to the target motion model prediction (usually a gaussian with 0 mean and around 30m/s^2 stddev). With this stddev, particles don't usually spread too much. Since we don't perform the fuseTarget() update when we have no vision to it (obviously), the weight sum does not approach zero and resampling occurs.

3. When target is seen again by the robots, the fuseTarget update mismatches all particles and usually the particle's weight sum will approach zero. When this happens and the filter stops resampling, I applied a modification to the target model prediction to around 300m/s^2 stddev, causing the particles to spread over the whole field, and usually at least one will have some weight by matching the target's observations. Due to the particle filter update steps, the higher weights for subparticles are combined and convergence is achieved quickly (some iterations). *see note

4. After a non-zero weight sum, the target motion model is reset to the default model.

note: **If convergence is not achieved quickly, it may cause the robots' subparticle sets to diverge too much, in which case the target observations will not match with the particles and convergence may never be achieved.** It's an avalanche situation. I think we should investigate this case in case it ever shows up during benchmarks.

**Comment by aamirahmad** [comment]
"When target is seen again by the robots, the fuseTarget update mismatches all particles and usually the particle's weight sum will approach zero" ... We need to rethink this particular part. Good that you raised/found it. Lets talk about it in the next meeting.
