### ISSUE TITLE
Move to a K-means approach

### ISSUE THREAD

**Issue by guilhermelawless** [guilhermelawless/pfuclt_omni_dataset#15]
We currently see some clusters of particles when resampling stops. If we could use a K-means approach and select the best cluster (with more added weight) we could probably improve our estimation.

As an idea, would this work for a resampling approach as well?

**Comment by aamirahmad** [comment]
Just to be sure again, enhancements are all for post-submission time (for next paper :D) so yeah, this is what I meant by red flag in the last comment on the odometry issue. Please add the enhancement label to it.
